import { getInstrument, SDOH30_QUESTIONS } from './instruments'
import { ZONE_WEIGHTS, SDOH6_ZONE_MAP, type ZoneCode } from '../scoring/givecareScore'

/**
 * The shared, machine-readable projection of the public SDOH instruments.
 *
 * gc-tools owns the instrument definition. This snapshot is the canonical
 * artifact downstream copies gate against:
 *   - `../gc-evals/scripts/validate.py` parity-checks its distribution records
 *     against `data/instruments-export.json`.
 *   - The production runtime (`../gc-sms/src/scoring.ts`) is documented as
 *     intentionally divergent in `data/production-delta.json`.
 *
 * Only the fields that must not silently drift live here: instrument ids,
 * question ids + prompts, per-question zones (where the instrument defines one),
 * and the composite zone weights. Human-facing packaging copy (titles,
 * descriptions, cadence, license notes, band labels) stays in the gc-evals
 * distribution record, not in the code definition.
 */
export interface ExportedQuestion {
  readonly id: string
  readonly prompt: string
  /** Present for zone-anchored instruments (SDOH-6, SDOH-30); absent for the
   * multi-mapped EMA-3, whose items fan out to more than one zone in scoring. */
  readonly zone?: ZoneCode
}

export interface InstrumentExport {
  readonly note: string
  readonly version: string
  readonly instruments: {
    readonly sdoh6: readonly ExportedQuestion[]
    readonly ema3: readonly ExportedQuestion[]
    readonly sdoh30: readonly ExportedQuestion[]
  }
  readonly zoneWeights: Readonly<Record<ZoneCode, number>>
}

const EXPORT_NOTE =
  'Canonical shared SDOH instrument definition, generated by ' +
  '`npm run export:instruments` from src/assessments/instruments.ts (@givecare/tools). ' +
  'gc-tools owns this definition; downstream copies (gc-evals distribution records, ' +
  'gc-sms production runtime) gate against it. Do not hand-edit — re-run the exporter.'

/** Build the deterministic shared-instrument snapshot from the source of truth. */
export function buildInstrumentExport(): InstrumentExport {
  const sdoh6: ExportedQuestion[] = getInstrument('sdoh6').questions.map(q => ({
    id: q.id,
    prompt: q.prompt,
    zone: SDOH6_ZONE_MAP[q.id],
  }))
  const ema3: ExportedQuestion[] = getInstrument('ema3').questions.map(q => ({
    id: q.id,
    prompt: q.prompt,
  }))
  const sdoh30: ExportedQuestion[] = SDOH30_QUESTIONS.map(q => ({
    id: q.id,
    prompt: q.prompt,
    zone: q.zone,
  }))

  return {
    note: EXPORT_NOTE,
    version: getInstrument('sdoh6').version,
    instruments: { sdoh6, ema3, sdoh30 },
    zoneWeights: ZONE_WEIGHTS,
  }
}
