// Area code -> IANA timezone (US-focused, best-effort)
const AREA_CODE_TZ: Record<string, string> = {
  // Eastern
  '201': 'America/New_York',
  '202': 'America/New_York',
  '203': 'America/New_York',
  '212': 'America/New_York',
  '215': 'America/New_York',
  '216': 'America/New_York',
  '267': 'America/New_York',
  '301': 'America/New_York',
  '302': 'America/New_York',
  '305': 'America/New_York',
  '315': 'America/New_York',
  '347': 'America/New_York',
  '404': 'America/New_York',
  '407': 'America/New_York',
  '410': 'America/New_York',
  '412': 'America/New_York',
  '413': 'America/New_York',
  '443': 'America/New_York',
  '484': 'America/New_York',
  '516': 'America/New_York',
  '518': 'America/New_York',
  '551': 'America/New_York',
  '561': 'America/New_York',
  '571': 'America/New_York',
  '585': 'America/New_York',
  '607': 'America/New_York',
  '610': 'America/New_York',
  '617': 'America/New_York',
  '631': 'America/New_York',
  '646': 'America/New_York',
  '678': 'America/New_York',
  '703': 'America/New_York',
  '704': 'America/New_York',
  '706': 'America/New_York',
  '716': 'America/New_York',
  '718': 'America/New_York',
  '732': 'America/New_York',
  '757': 'America/New_York',
  '770': 'America/New_York',
  '772': 'America/New_York',
  '774': 'America/New_York',
  '781': 'America/New_York',
  '786': 'America/New_York',
  '802': 'America/New_York',
  '803': 'America/New_York',
  '804': 'America/New_York',
  '813': 'America/New_York',
  '828': 'America/New_York',
  '845': 'America/New_York',
  '856': 'America/New_York',
  '857': 'America/New_York',
  '860': 'America/New_York',
  '862': 'America/New_York',
  '863': 'America/New_York',
  '904': 'America/New_York',
  '908': 'America/New_York',
  '910': 'America/New_York',
  '914': 'America/New_York',
  '917': 'America/New_York',
  '919': 'America/New_York',
  '929': 'America/New_York',
  '954': 'America/New_York',
  '973': 'America/New_York',
  // Central
  '205': 'America/Chicago',
  '210': 'America/Chicago',
  '214': 'America/Chicago',
  '217': 'America/Chicago',
  '224': 'America/Chicago',
  '225': 'America/Chicago',
  '254': 'America/Chicago',
  '262': 'America/Chicago',
  '281': 'America/Chicago',
  '309': 'America/Chicago',
  '312': 'America/Chicago',
  '314': 'America/Chicago',
  '316': 'America/Chicago',
  '317': 'America/Chicago',
  '318': 'America/Chicago',
  '319': 'America/Chicago',
  '320': 'America/Chicago',
  '325': 'America/Chicago',
  '331': 'America/Chicago',
  '334': 'America/Chicago',
  '337': 'America/Chicago',
  '361': 'America/Chicago',
  '405': 'America/Chicago',
  '409': 'America/Chicago',
  '414': 'America/Chicago',
  '417': 'America/Chicago',
  '430': 'America/Chicago',
  '469': 'America/Chicago',
  '479': 'America/Chicago',
  '501': 'America/Chicago',
  '504': 'America/Chicago',
  '507': 'America/Chicago',
  '512': 'America/Chicago',
  '515': 'America/Chicago',
  '531': 'America/Chicago',
  '563': 'America/Chicago',
  '573': 'America/Chicago',
  '601': 'America/Chicago',
  '612': 'America/Chicago',
  '615': 'America/Chicago',
  '618': 'America/Chicago',
  '630': 'America/Chicago',
  '651': 'America/Chicago',
  '662': 'America/Chicago',
  '682': 'America/Chicago',
  '708': 'America/Chicago',
  '713': 'America/Chicago',
  '715': 'America/Chicago',
  '726': 'America/Chicago',
  '731': 'America/Chicago',
  '737': 'America/Chicago',
  '773': 'America/Chicago',
  '779': 'America/Chicago',
  '806': 'America/Chicago',
  '815': 'America/Chicago',
  '816': 'America/Chicago',
  '817': 'America/Chicago',
  '830': 'America/Chicago',
  '832': 'America/Chicago',
  '847': 'America/Chicago',
  '850': 'America/Chicago',
  '870': 'America/Chicago',
  '901': 'America/Chicago',
  '903': 'America/Chicago',
  '913': 'America/Chicago',
  '918': 'America/Chicago',
  '920': 'America/Chicago',
  '936': 'America/Chicago',
  '940': 'America/Chicago',
  '952': 'America/Chicago',
  '956': 'America/Chicago',
  '972': 'America/Chicago',
  '979': 'America/Chicago',
  // Mountain
  '303': 'America/Denver',
  '307': 'America/Denver',
  '385': 'America/Denver',
  '406': 'America/Denver',
  '435': 'America/Denver',
  '480': 'America/Denver',
  '505': 'America/Denver',
  '520': 'America/Denver',
  '575': 'America/Denver',
  '602': 'America/Denver',
  '623': 'America/Denver',
  '719': 'America/Denver',
  '720': 'America/Denver',
  '801': 'America/Denver',
  '928': 'America/Denver',
  // Pacific
  '206': 'America/Los_Angeles',
  '208': 'America/Los_Angeles',
  '209': 'America/Los_Angeles',
  '213': 'America/Los_Angeles',
  '253': 'America/Los_Angeles',
  '310': 'America/Los_Angeles',
  '323': 'America/Los_Angeles',
  '360': 'America/Los_Angeles',
  '408': 'America/Los_Angeles',
  '415': 'America/Los_Angeles',
  '425': 'America/Los_Angeles',
  '442': 'America/Los_Angeles',
  '503': 'America/Los_Angeles',
  '509': 'America/Los_Angeles',
  '510': 'America/Los_Angeles',
  '530': 'America/Los_Angeles',
  '541': 'America/Los_Angeles',
  '559': 'America/Los_Angeles',
  '562': 'America/Los_Angeles',
  '619': 'America/Los_Angeles',
  '626': 'America/Los_Angeles',
  '650': 'America/Los_Angeles',
  '657': 'America/Los_Angeles',
  '661': 'America/Los_Angeles',
  '669': 'America/Los_Angeles',
  '702': 'America/Los_Angeles',
  '707': 'America/Los_Angeles',
  '714': 'America/Los_Angeles',
  '725': 'America/Los_Angeles',
  '747': 'America/Los_Angeles',
  '760': 'America/Los_Angeles',
  '775': 'America/Los_Angeles',
  '805': 'America/Los_Angeles',
  '818': 'America/Los_Angeles',
  '831': 'America/Los_Angeles',
  '858': 'America/Los_Angeles',
  '909': 'America/Los_Angeles',
  '916': 'America/Los_Angeles',
  '925': 'America/Los_Angeles',
  '949': 'America/Los_Angeles',
  '951': 'America/Los_Angeles',
  '971': 'America/Los_Angeles',
  // Alaska / Hawaii
  '907': 'America/Anchorage',
  '808': 'Pacific/Honolulu',
}

const TZ_KEYWORD_MAP: Record<string, string> = {
  eastern: 'America/New_York',
  est: 'America/New_York',
  et: 'America/New_York',
  central: 'America/Chicago',
  cst: 'America/Chicago',
  ct: 'America/Chicago',
  mountain: 'America/Denver',
  mst: 'America/Denver',
  mt: 'America/Denver',
  pacific: 'America/Los_Angeles',
  pst: 'America/Los_Angeles',
  pt: 'America/Los_Angeles',
  alaska: 'America/Anchorage',
  akst: 'America/Anchorage',
  hawaii: 'Pacific/Honolulu',
  hst: 'Pacific/Honolulu',
}

export const TZ_DISPLAY_NAME: Record<string, string> = {
  'America/New_York': 'Eastern',
  'America/Chicago': 'Central',
  'America/Denver': 'Mountain',
  'America/Los_Angeles': 'Pacific',
  'America/Anchorage': 'Alaska',
  'Pacific/Honolulu': 'Hawaii',
}

const CONFIRM_PATTERN =
  /^\s*(yes|yep|yeah|y|ok|okay|sure|correct|right|that's right|that works|sounds right)\b/i

export function inferTimezoneFromAreaCode(phoneE164: string): string {
  if (phoneE164.startsWith('+1') && phoneE164.length >= 5) {
    const areaCode = phoneE164.slice(2, 5)
    return AREA_CODE_TZ[areaCode] ?? 'America/New_York'
  }
  return 'America/New_York'
}

export function parseTimezoneResponse(text: string, inferredTz: string): string {
  const trimmed = text.trim()
  if (!trimmed || /^\s*(skip|next|pass|no|nah|later)\s*$/i.test(trimmed)) return inferredTz
  if (CONFIRM_PATTERN.test(trimmed)) return inferredTz
  const lower = trimmed.toLowerCase()
  for (const [keyword, tz] of Object.entries(TZ_KEYWORD_MAP)) {
    if (lower.includes(keyword)) return tz
  }
  return inferredTz
}
